env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  linebreak-style:
    - off
  semi:
    - error
    - always
  prettier/prettier:
    - error
  no-undef:
    - off
  '@typescript-eslint/no-var-requires':
    - off
  '@typescript-eslint/no-empty-function':
    - off
  '@typescript-eslint/ban-types':
    - warn
  '@typescript-eslint/ban-ts-comment':
    - off
