name: Lint

on:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
  ci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint ESlint
        run: yarn lint
